print ("hello world!")
print ()            # this is used to make a blank line
print ("What is your name?")
print ()
myName = input()
print ()
print ("It is good to meet you, " + myName)
print ()
print ("The length of your name is: ")
print ()
print (len(myName))
print ()
print ("What is your age?")
print ()
myAge = input()
print ()
print ("You will be " + str(int(myAge)+1) + "in a year.")
